In [54]:
import numpy as np

# Истинные значения и предсказанные значения
y_true = ["Cat", "Cat", "Cat", "Cat", "Cat", "Cat", "Fish", "Fish", "Fish",
          "Fish", "Fish", "Fish", "Fish", "Fish", "Fish", "Fish", "Hen", "Hen",
          "Hen", "Hen", "Hen", "Hen", "Hen", "Hen", "Hen"]
y_pred = ["Cat", "Cat", "Cat", "Cat", "Hen", "Fish", "Cat", "Cat", "Cat", "Cat",
          "Cat", "Cat", "Hen", "Hen", "Fish", "Fish", "Cat", "Cat", "Cat", "Hen",
          "Hen", "Hen", "Hen", "Hen", "Hen"]

# Создаем список уникальных классов
classes = ["Cat", "Fish", "Hen"]

# Инициализируем матрицу confusion нулями (чтобы привезти к виду вывода из
# задания, принудительно указываем int тип для данных в матрице)
confusion_matrix = np.zeros((len(classes), len(classes)), dtype=int)

# Заполняем матрицу confusion
for true, pred in zip(y_true, y_pred):
    true_idx = classes.index(true)
    pred_idx = classes.index(pred)
    confusion_matrix[true_idx][pred_idx] += 1

# Выводим матрицу confusion
print(confusion_matrix)

# Вычисляем метрики precision, recall и f1-score для каждого класса
precision = np.zeros(len(classes))
recall = np.zeros(len(classes))
f1_score = np.zeros(len(classes))
support = np.zeros(len(classes))

for i in range(len(classes)):
    true_positives = confusion_matrix[i, i]
    false_positives = np.sum(confusion_matrix[:, i]) - true_positives
    false_negatives = np.sum(confusion_matrix[i, :]) - true_positives

    precision[i] = true_positives / (true_positives + false_positives)
    recall[i] = true_positives / (true_positives + false_negatives)
    f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i])
    support[i] = np.sum(confusion_matrix[i, :])

# Вычисляем accuracy и метрики для всего набора данных
accuracy = np.sum(np.diag(confusion_matrix)) / np.sum(confusion_matrix)
macro_avg_precision = np.mean(precision)
macro_avg_recall = np.mean(recall)
macro_avg_f1_score = np.mean(f1_score)

weighted_avg_precision = np.sum(precision * support) / np.sum(support)
weighted_avg_recall = np.sum(recall * support) / np.sum(support)
weighted_avg_f1_score = np.sum(f1_score * support) / np.sum(support)

# Выводим метрики для каждого класса
print(f"\n{'':<10}{'Precision':<10}{'Recall':<10}{'F1-Score':<10}{'Support':<10}\n")
for i, class_name in enumerate(classes):
    print(f"{class_name:<10}{precision[i]:<10.3f}{recall[i]:<10.3f}{f1_score[i]:<10.3f}{int(support[i]):<10}")

# Вычисляем accuracy и метрики для всего набора данных
accuracy = np.sum(np.diag(confusion_matrix)) / np.sum(confusion_matrix)
macro_avg_precision = np.mean(precision)
macro_avg_recall = np.mean(recall)
macro_avg_f1_score = np.mean(f1_score)

weighted_avg_precision = np.sum(precision * support) / np.sum(support)
weighted_avg_recall = np.sum(recall * support) / np.sum(support)
weighted_avg_f1_score = np.sum(f1_score * support) / np.sum(support)

# Выводим метрики для каждого класса и общие метрики
print(f"\n{'Accuracy':<10}{accuracy:>25.3f}{int(np.sum(support)):7}")
print(f"{'Macro Avg':<10}{macro_avg_precision:.3f}{macro_avg_recall:10.3f}{macro_avg_f1_score:10.3f}{int(np.sum(support)):7}")
print(f"{'W-ted Avg':<10}{weighted_avg_precision:.3f}{weighted_avg_recall:10.3f}{weighted_avg_f1_score:10.3f}{int(np.sum(support)):7}")

[[4 1 1]
 [6 2 2]
 [3 0 6]]

          Precision Recall    F1-Score  Support   

Cat       0.308     0.667     0.421     6         
Fish      0.667     0.200     0.308     10        
Hen       0.667     0.667     0.667     9         

  Accuracy                    0.480     25
Macro Avg 0.547     0.511     0.465     25
W-ted Avg 0.581     0.480     0.464     25
